server:
  port: 80
#  servlet:
#    #项目路径
#    context-path: /yjxt
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stxt?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  #配置别名
  type-aliases-package: com.core.stxt.sys.entity
  configuration:
    auto-mapping-behavior: full
    #默认打印SQL语句使用的日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #扫描xml
  mapper-locations: classpath:mapper/*.xml

